server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /api
    session:
      cookie:
        name: NE_SESSION
        path: /

capabilities:
  filepath: /tmp/capabilities.json
  cache.ttl: PT60S

### Security Properties ###
security:
  admin-emails:
#### EOSC AAI Authentication ####
spring:
  security:
    oauth2:
      client:
        provider:
          eosc:
            issuer-uri: issuer-uri
        registration:
          eosc:
            client-id:
            client-name: EOSC
            client-secret:
            scope: openid,email,profile,entitlements

      resourceserver.jwt.issuer-uri: ${spring.security.oauth2.client.provider.eosc.issuer-uri}