capabilities.filepath=/app/config/capabilities.json

### Security Properties ###
security.admin-emails=${ADMIN_EMAILS}
security.login-redirect=http://localhost:4200/admin/
security.logout-redirect=http://localhost:4200/admin/
#### EOSC AAI Authentication ####
spring.security.oauth2.client.provider.eosc.issuer-uri=${ISSUER_URI}
spring.security.oauth2.client.registration.eosc.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.eosc.client-name=EOSC
spring.security.oauth2.client.registration.eosc.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.eosc.scope=openid,email,profile
spring.security.oauth2.client.registration.eosc.authorization-grant-type=authorization_code
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}